export const BASE_PROMPTS: Record<string, string[]> = {
    "Item displacement": [
        "picking up house keys from a table",
        "placing a leather wallet on a counter",
        "grabbing sunglasses from a desk",
        "putting wireless earphones into a case",
        "moving a wallet from a pocket to a table",
        "picking up a set of car keys",
        "setting reading glasses down on a nightstand",
        "grabbing a keychain before leaving",
        "holding a wallet to open it",
        "picking up earphones from a desk",
        "placing keys into a small bowl",
        "moving glasses across a table",
        "putting a wallet back into a pocket",
        "holding reading glasses by the frame",
        "picking up a lanyard with keys",
        "placing a cardholder on a desk",
        "grabbing earbuds from a nightstand",
        "moving a keychain from hand to table",
        "picking up a pair of eyeglasses",
        "setting down a bi-fold wallet"
    ],
    "Health and habit": [
        "opening a plastic pill bottle",
        "popping a pill out of a foil blister pack",
        "holding a daily vitamin tablet",
        "picking up a reusable water bottle",
        "unscrewing the cap of a medicine bottle",
        "pouring pills into the palm of a hand",
        "taking a sip from a sports water bottle",
        "holding a prescription medication bottle",
        "pressing out a pill from a blister pack",
        "drinking from an insulated water flask",
        "picking up a weekly pill organizer",
        "twisting the lid off a water bottle",
        "holding a capsule medication",
        "taking a drink from a hydro flask",
        "opening a compartment of a pill dispenser",
        "holding a multivitamin gummy",
        "picking up a plastic water bottle",
        "looking at a medication label",
        "grabbing a supplement bottle",
        "holding a glass of water and a pill"
    ],
    "Buying objects": [
        "placing a grocery item into a shopping cart",
        "picking up a product from a retail shelf",
        "holding a box of cereal in a supermarket",
        "putting fresh produce into a shopping basket",
        "examining a product label in a store",
        "grabbing a bottle from a store aisle",
        "placing a canned good into a cart",
        "picking up a piece of clothing from a rack",
        "holding a retail item to check the price",
        "dropping an item into a hand basket",
        "taking a product off a display hook",
        "holding a bag of chips in a grocery store",
        "placing a selected item into a shopping trolley",
        "picking out fruit from a market bin",
        "looking at a product on a store shelf",
        "grabbing an item from a freezer door",
        "putting a packaged product into a cart",
        "holding a retail box in an aisle",
        "selecting an item from a store display",
        "picking up goods for purchase"
    ],
    "Paying for objects": [
        "tapping a credit card on a payment terminal",
        "handing cash to a store cashier",
        "holding a printed store receipt",
        "scanning a QR code with a smartphone to pay",
        "inserting a chip card into a card reader",
        "receiving change from a cash register",
        "holding a credit card over a contactless reader",
        "looking at a grocery store receipt",
        "counting paper money to pay",
        "pulling a credit card out of a wallet",
        "holding out cash to make a purchase",
        "looking at the screen of a point of sale terminal",
        "receiving a paper receipt from a cashier",
        "holding a smartphone to a payment reader",
        "typing a PIN on a payment terminal",
        "handing a credit card to a cashier",
        "checking the total on a checkout screen",
        "holding cash and coins",
        "taking a receipt from a printer",
        "finalizing a transaction at a checkout counter"
    ],
    "Using smartphone or computer": [
        "scrolling through an app on a smartphone",
        "opening the lid of a laptop computer",
        "typing on a laptop keyboard",
        "holding a smartphone to read a message",
        "using a computer mouse on a desk",
        "looking at a glowing laptop screen",
        "tapping the screen of a mobile phone",
        "resting hands on a desktop keyboard",
        "typing an email on a computer",
        "holding a smartphone in landscape mode",
        "navigating a website on a laptop",
        "pressing keys on a mechanical keyboard",
        "looking at a smartphone notification",
        "using a trackpad on a laptop",
        "texting on a touch screen phone",
        "closing a laptop computer",
        "clicking a mouse button",
        "watching a video on a smartphone",
        "looking at code on a computer monitor",
        "holding a mobile phone in one hand"
    ],
    "Exiting place": [
        "opening a front door to leave a house",
        "walking through an exit door",
        "pushing a glass door open to leave a building",
        "stepping out of a doorway onto a porch",
        "closing a front door behind oneself",
        "turning a doorknob to exit a room",
        "walking out of an office building",
        "stepping over a door threshold to go outside",
        "pushing an exit bar on a commercial door",
        "leaving a building through a sliding glass door",
        "opening an apartment door to leave",
        "stepping out onto a sidewalk from a doorway",
        "pulling a door shut when leaving",
        "walking through a doorframe to the outside",
        "leaving a room and entering a hallway",
        "opening a wooden door to head out",
        "stepping outdoors from an indoor space",
        "locking a front door with a key after exiting",
        "passing through double doors to leave",
        "crossing a threshold from indoors to outdoors"
    ],
    "Exiting car": [
        "opening a car door from the inside",
        "stepping out of the driver's seat of a car",
        "pushing a car door open to exit",
        "stepping down from a bus onto the sidewalk",
        "grabbing a car door handle from the inside",
        "exiting a passenger seat of a vehicle",
        "stepping out of a train car",
        "closing a car door from the outside",
        "getting out of an SUV",
        "stepping off a public transit bus",
        "opening the door of a parked car",
        "stepping onto the pavement from a car",
        "unbuckling a seatbelt before exiting a car",
        "walking out of a subway train door",
        "getting out of a taxi cab",
        "pushing open a heavy car door",
        "standing up from a car seat",
        "exiting a vehicle into a parking lot",
        "stepping off a commuter train",
        "shutting a vehicle door after getting out"
    ]
};

export const SEMANTIC_CATEGORIES: Record<string, string[]> = Object.fromEntries(
    Object.entries(BASE_PROMPTS).map(([category, prompts]) => {
        const expandedPrompts = [
            ...prompts,                                       // Original 20
            ...prompts.map(p => `POV: ${p}`),                 // +20 (Point of view modifier)
            ...prompts.map(p => `first-person view of ${p}`), // +20 (First-person modifier)
            ...prompts.map(p => `close up: ${p}`)             // +20 (Close up modifier)
        ];
        return [category, expandedPrompts];
    })
);
