import { create } from 'zustand';
import { supabase } from './supabase_client';


interface ClipFile {
    uri: string;
    name?: string;
    type?: string; // e.g., 'video/mp4'
}

interface Location {
    lat: number,
    long: number,
}

interface Clip {
    id?: string; // generated by DB
    user_id: string;
    video_url: string;
    title?: string | null; // Nullable in DB, populated by trigger later
    thumbnail_url?: string | null;
    recorded_at: string;
    summary?: string | null;
    location?: Location | null;
    created_at?: string;
}

type DateRange = 'day' | 'week' | 'month';
interface ClipsDatabaseManagement {
    uploading: boolean;
    deleting: boolean;
    clips: Clip[];
    error: string | null;

    // Actions
    uploadClip: (file: ClipFile, userId: string, metadata: { location?: Location; recordedAt: Date }) => Promise<void>;
    getUserClips: (userId: string) => Promise<void>;
    getClipsByDate: (userId: string, range: DateRange) => Promise<Clip[]>;
    deleteClipsOlderThanDays: (userId: string, days: number) => Promise<void>;
}


const getStartDate = (range: DateRange): string => {
    const d = new Date();
    if (range === 'day') d.setDate(d.getDate() - 1);      // Last 24 hours
    if (range === 'week') d.setDate(d.getDate() - 7);     // Last 7 days
    if (range === 'month') d.setMonth(d.getMonth() - 1);  // Last 30 days
    return d.toISOString();
};

export const useClipsStore = create<ClipsDatabaseManagement>((set, get) => ({
    uploading: false,
    deleting: false,
    clips: [],
    error: null,

    uploadClip: async (file, userId, metadata) => {
        set({ uploading: true, error: null });

        try {
            // Step 1: Prepare the file for upload
            const formData = new FormData();
            formData.append('file', {
                uri: file.uri,
                name: file.name || `clip_${new Date().getTime()}.mp4`,
                type: file.type || 'video/mp4',
            } as any);

            // Create a unique file path: user_id/timestamp.mp4
            const fileName = `${new Date().getTime()}.mp4`;
            const filePath = `${userId}/${fileName}`;

            // Step 2: Upload to Supabase Storage ('clips' bucket)
            const { data: storageData, error: storageError } = await supabase.storage
                .from('clips')
                .upload(filePath, formData);

            if (storageError) throw storageError;

            // Step 3: Get the Public URL
            const { data: { publicUrl } } = supabase.storage
                .from('clips')
                .getPublicUrl(filePath);

            // Step 4: Insert record into the Database
            const newClipPayload = {
                user_id: userId,
                video_url: publicUrl,
                recorded_at: metadata.recordedAt.toISOString(),
                location: metadata.location || null,
            };

            const { data: dbData, error: dbError } = await supabase
                .from('clips') // Replace with your actual table name
                .insert(newClipPayload)
                .select()
                .single();

            if (dbError) throw dbError;

            // Optimistic update or refetch
            const currentClips = get().clips;
            set({ clips: [dbData, ...currentClips], uploading: false });

            console.log('Upload successful, trigger should fire now.');

        } catch (error: any) {
            console.error('Upload failed:', error);
            set({ uploading: false, error: error.message });
        }
    },

    getUserClips: async (userId: string) => {
        set({ error: null });
        try {
            const { data, error } = await supabase
                .from('clips')
                .select('*')
                .eq('user_id', userId)
                .order('recorded_at', { ascending: false });

            if (error) throw error;

            set({ clips: data || [] });
        } catch (error: any) {
            set({ error: error.message });
        }
    },

    getClipsByDate: async (userId: string, range: DateRange) => {
        set({ error: null });
        const startDate = getStartDate(range);

        try {
            const { data, error } = await supabase
                .from('clips')
                .select('*')
                .eq('user_id', userId)
                .gte('recorded_at', startDate)
                .order('recorded_at', { ascending: false });

            if (error) throw error;

            const fetchedClips = data || [];

            set({ clips: fetchedClips });

            return fetchedClips;

        } catch (error: any) {
            console.error('Error fetching by date:', error);
            set({ error: error.message });
            return [];
        }
    },

    deleteClipsOlderThanDays: async (userId: string, days: number) => {
        set({ deleting: true, error: null });
        const cutoffDate = new Date();
        cutoffDate.setDate(cutoffDate.getDate() - days);

        try {
            // 1. Identify clips to delete (we need their video_urls to delete files from Storage)
            const { data: clipsToDelete, error: fetchError } = await supabase
                .from('clips')
                .select('video_url')
                .eq('user_id', userId)
                .lt('recorded_at', cutoffDate.toISOString());

            if (fetchError) throw fetchError;

            if (clipsToDelete && clipsToDelete.length > 0) {

                // 2. Extract file paths from URLs
                // URL: https://.../clips/USER_ID/FILENAME.mp4
                // We need: USER_ID/FILENAME.mp4
                const filePaths = clipsToDelete.map(clip => {
                    const parts = clip.video_url.split('/clips/'); // Split by bucket name
                    return parts[1]; // Get the path after the bucket name
                }).filter(path => path); // ensure no undefined paths

                // 3. Delete files from Storage Bucket
                if (filePaths.length > 0) {
                    const { error: storageError } = await supabase.storage
                        .from('clips')
                        .remove(filePaths);
                    if (storageError) console.error("Storage cleanup warning:", storageError);
                }

                // 4. Delete rows from Database
                const { error: deleteError } = await supabase
                    .from('clips')
                    .delete()
                    .eq('user_id', userId)
                    .lt('recorded_at', cutoffDate.toISOString());

                if (deleteError) throw deleteError;

                // 5. Update local state
                // Filter out the deleted clips from the local list so UI updates instantly
                const remainingClips = get().clips.filter(clip => {
                    return new Date(clip.recorded_at) >= new Date(cutoffDate);
                });
                set({ clips: remainingClips });
            }

            set({ uploading: false });

        } catch (error: any) {
            console.error('Delete failed:', error);
            set({ uploading: false, error: error.message });
        }
    }

}));