import { create } from 'zustand';
import { supabase } from '../databases/supabase/supabase_client';


interface ClipFile {
    uri: string;
    name?: string;
    type?: string; // e.g., 'video/mp4'
}

interface Location {
    lat: number,
    long: number,
}

interface Clip {
    id?: string; // generated by DB
    user_id: string;
    video_url: string;
    title?: string | null; // Nullable in DB, populated by trigger later
    thumbnail_url?: string | null;
    recorded_at: string;
    summary?: string | null;
    location?: Location | null;
    created_at?: string;
}

interface ClipsDatabaseManagement {
    uploading: boolean;
    clips: Clip[];
    error: string | null;

    // Actions
    uploadClip: (file: ClipFile, userId: string, metadata: { location?: Location; recordedAt: Date }) => Promise<void>;
    getUserClips: (userId: string) => Promise<void>;
}


export const useClipsStore = create<ClipsDatabaseManagement>((set, get) => ({
    uploading: false,
    clips: [],
    error: null,

    uploadClip: async (file, userId, metadata) => {
        set({ uploading: true, error: null });

        try {
            // Step 1: Prepare the file for upload
            const formData = new FormData();
            formData.append('file', {
                uri: file.uri,
                name: file.name || `clip_${new Date().getTime()}.mp4`,
                type: file.type || 'video/mp4',
            } as any);

            // Create a unique file path: user_id/timestamp.mp4
            const fileName = `${new Date().getTime()}.mp4`;
            const filePath = `${userId}/${fileName}`;

            // Step 2: Upload to Supabase Storage ('clips' bucket)
            const { data: storageData, error: storageError } = await supabase.storage
                .from('clips')
                .upload(filePath, formData);

            if (storageError) throw storageError;

            // Step 3: Get the Public URL
            const { data: { publicUrl } } = supabase.storage
                .from('clips')
                .getPublicUrl(filePath);

            // Step 4: Insert record into the Database
            const newClipPayload = {
                user_id: userId,
                video_url: publicUrl,
                recorded_at: metadata.recordedAt.toISOString(),
                location: metadata.location || null,
            };

            const { data: dbData, error: dbError } = await supabase
                .from('clips') // Replace with your actual table name
                .insert(newClipPayload)
                .select()
                .single();

            if (dbError) throw dbError;

            // Optimistic update or refetch
            const currentClips = get().clips;
            set({ clips: [dbData, ...currentClips], uploading: false });

            console.log('Upload successful, trigger should fire now.');

        } catch (error: any) {
            console.error('Upload failed:', error);
            set({ uploading: false, error: error.message });
        }
    },

    getUserClips: async (userId: string) => {
        set({ error: null });
        try {
            const { data, error } = await supabase
                .from('clips')
                .select('*')
                .eq('user_id', userId)
                .order('recorded_at', { ascending: false });

            if (error) throw error;

            set({ clips: data || [] });
        } catch (error: any) {
            set({ error: error.message });
        }
    },
}));